import Head from "next/head";

export default function PXToRem() {
    return (
        <>
            <Head>
                <title>PX to REM - Calculators | tools.benjaminschober.de</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>hi</div>
        </>
    );
}
