import { Container, Grid } from "@mantine/core";
import Head from "next/head";
import React, { useRef } from "react";
import { ControlledNumberInput } from "../../components/input/ControlledNumberInput";
import { Calculators } from "../../types/enums";
import { ControlledNumberInputRef } from "../../types/refs";

export default function PXToRem() {
    const childFunc = useRef<ControlledNumberInputRef>();

    const valueSync = (value: number, type: Calculators) => {
        console.log(value, type);
        if(childFunc.current) {
            console.log("childFunc.current", childFunc.current, value);
            childFunc.current.changeValue(value);
        }
    };

    return (
        <>
            <Head>
                <title>
                    PX to REM - Calculators | tools.benjaminschober.de
                </title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Container>
                <Grid>
                    <Grid.Col span={4}>
                        <ControlledNumberInput
                            onChange={valueSync}
                            type={Calculators.PX}
                            //ref={childFunc} // does not work
                        />
                    </Grid.Col>
                    <Grid.Col span={4} style={{ textAlign: "center" }}>
                        =
                    </Grid.Col>
                    <Grid.Col span={4}>
                        <ControlledNumberInput
                            onChange={valueSync}
                            type={Calculators.REM}
                        />
                    </Grid.Col>
                </Grid>
            </Container>
        </>
    );
}
