import React, { useEffect, useState } from "react";
import { GetServerSideProps } from "next";
import Link from "next/link";
import { useRouter } from "next/router";
import Head from "next/head";
import { signIn, getSession } from "next-auth/react";
import { Container, Title, Text, Anchor, Alert, Space } from "@mantine/core";
import { useDocumentTitle, useToggle } from "@mantine/hooks";
import { IoAlertCircleOutline } from "react-icons/io5";
import LoginComponent from "../../../components/Login";
import { LoginPageProps } from "../../../types/interfaces";
import { getLastRoute } from "../../../utils/appHandles";
import { ForgotPassword } from "../../../components/ForgotPassword";

export default function LoginPage({ session }: LoginPageProps) {
    const [isPasswordForgotten, setIsPasswordForgotten] = useToggle(false, [
        false,
        true,
    ]);

    // create a custom hook, that does this all automatically?
    const [pageTitle, setPageTitle] = useState("Login");
    useDocumentTitle(pageTitle);

    const router = useRouter();

    useEffect(() => {
        if (router && router.query) {
            handleSession();
        }

        if (window && document) {
            setPageTitle(document.title + " | " + window.location.hostname);
        }
    }, [router]);

    const handleSession = () => {
        if (
            session &&
            session.status === "authorized" &&
            router.query &&
            router.query.from
        ) {
            let route = getLastRoute(router);
            router.push(route);
            return;
        }
        if (session && session.status === "authorized") router.push("/");
    };

    const handleLogin = (
        username: string,
        password: string,
        remember: boolean
    ) => {
        signIn("credentials", {
            username: username,
            password: password,
        });
    };

    const handlePasswordForgotten = () => {
        setIsPasswordForgotten();
    };

    return (
        <>
            <Head>
                <title>{pageTitle}</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Container size={420} my={40}>
                <Title
                    align="center"
                    sx={(theme) => ({
                        fontFamily: `Greycliff CF, ${theme.fontFamily}`,
                        fontWeight: 900,
                    })}
                >
                    {isPasswordForgotten
                        ? "Forgot your password?"
                        : "Welcome back!"}
                </Title>
                {isPasswordForgotten ? (
                    <ForgotPassword forgotPassword={handlePasswordForgotten} />
                ) : (
                    <LoginComponent
                        loginHandler={handleLogin}
                        forgotPassword={handlePasswordForgotten}
                    />
                )}
                {session?.status === "unauthorized" ? (
                    <>
                        <Space h="xl" />
                        <Alert
                            icon={<IoAlertCircleOutline size={16} />}
                            title="Wrong credentials!"
                            color="red"
                        >
                            The given credentials are not correct. Please try
                            again. If you have not yet created an account,
                            please{" "}
                            <Link href="/auth/register">
                                <Anchor<"a"> href="/auth/register" size="sm">
                                    register
                                </Anchor>
                            </Link>{" "}
                            first.
                        </Alert>
                        <Space h="xl" />
                    </>
                ) : (
                    <></>
                )}
                <Space h="xl" />
                <Text color="dimmed" size="sm" align="center" mt={5}>
                    Don`$apos`t want to login?{" "}
                    <Link href="/">
                        <Anchor<"a"> size="sm" href="/">
                            Back to Home
                        </Anchor>
                    </Link>
                </Text>
            </Container>
        </>
    );
}

export const getServerSideProps: GetServerSideProps = async (context) => {
    return {
        props: {
            session: await getSession(context),
        },
    };
};
